[pytest]

pythonpath=.

testpaths=tests

addopts=

    --headed
    --browser chromium
    --slowmo=300
    --html=reports/report.html
    --self-contained-html
    --alluredir=allure-results

markers =
    smoke
    regression
    sanity

log_cli=true

log_cli_level=INFO